@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

### 查询数据
GET http://{{host}}/api/console/startups/
    ?pagination[page]=1
    &pagination[pageSize]=25
    # &sort[field]=created
    # &sort[order]=desc
    # &filter[teamSize][<]=10
    # &filter[oneline][∋]='first'

### 注册用户
POST http://{{host}}/api/reception/signup/
Content-Type: {{contentType}}

{
  "name": "tester001",
  "password": "123456"
}

### 发送验证码
POST http://{{host}}/api/reception/verification/
Content-Type: {{contentType}}

{
  "identifier": "i@lishaoy.net"
}

### 验证码登录
POST http://{{host}}/api/reception/signin/
Content-Type: {{contentType}}

{
  "identifier": "i@lishaoy.net",
  "verification": "6457"
}

### 密码登录
POST http://{{host}}/api/reception/signin/
Content-Type: {{contentType}}

{
  "identifier": "i@lishaoy.net",
  "password": "123456"
}

### 带 Token 的查询
GET http://{{host}}/api/console/startups/
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJOUyI6ImhlaW1pYW8iLCJEQiI6ImFwcCIsIlNDIjoiY29tbW9uIiwiVEsiOiJoZWltaWFvIiwiSUQiOiJ1c2VyOjZ1ZThpNmZ4M3dmMHZiczZrbjQ1IiwibmFtZSI6InRlc3RlcjAwMSIsImlhdCI6MTczODkzOTEzNiwiZXhwIjoxNzQ2NzE1MTM2fQ.Kc_euOdQrilYXAHDRbFfH9Fu_-xDvsBz66v8dXoZLhZo0QyjmOnOiJNDnMfpXVnl2t8Oril_g3uSS_WxStkfto7ne_Uo3dVWzZK162KZEN-za3067cTrQbhEsdM--o71ZbPNBQ6CqghVBHOowPKciIMTw90ZflpbLul9cWga993_910J2bLRIII40ZTqWwiVPN1VGOkl7R9D4lt8F-738Ap8E_VjedKyhMwQL3ZIVRNOrHQiCZ3siK3UJtZMs3Z3atREhFAroj-isDR4GI0gc75cNSFEEz228IDeh5bzVs-MBRCNm_hQkkgOLaj1Bn67Tu9YB0hC-NNN_ptkGKv-GQ


