@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

### 查询数据
GET http://{{host}}/api/console/startups/
    ?pagination[page]=1
    &pagination[pageSize]=25
    # &sort[field]=created
    # &sort[order]=desc
    # &filter[teamSize][<]=10
    # &filter[oneline][∋]='first'

### 注册用户
POST http://{{host}}/api/reception/signup/
Content-Type: {{contentType}}

{
  "name": "Persilee",
  "password": "123456"
}

### 登录
POST http://{{host}}/api/reception/signin/
Content-Type: {{contentType}}

{
  "identifier": "i@lishaoy.net",
  "password": "123456"
}

### 验证用户名
POST http://{{host}}/api/reception/verification/
Content-Type: {{contentType}}

{
  "identifier": "i@lishaoy.net"
}
