@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/api/console/startups/
    ?pagination[page]=1
    &pagination[pageSize]=10

###
POST http://{{host}}/api/console/startups/
Content-Type: {{contentType}}

{
  "founder":"persilee",
  "name": "黑喵",
  "oneline": "~~~~"
}